name: CI → GitHub Pages

# make sure GITHUB_TOKEN has the right scopes
permissions:
  contents: read       # read from your repo
  pages: write         # allow Pages deployments
  id-token: write      # required by deploy-pages@v1

on:
  push:
    branches:
      - master         # (or 'main' if that’s your default branch)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.1

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test -- --watchAll=false

      - name: Build production bundle
        run: npm run build   # → outputs into dist/
      - name: Copy 404 fallback   # or use cpy-cli on Windows runners
        run: |
          cp dist/index.html dist/404.html     

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist         # ← point at your Vite output dir

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages   # special environment for Pages
    steps:
    
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deploy-pages
